# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/joescharf/wt/releases/download/v0.5.0/wt_darwin_universal.tar.gz"
  sha256 "521e04922ea517bdf650a67240ee73c9e1875a97b6001137464ff8c13484d347"

  def install
    bin.install "wt"
  end
end
