# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/joescharf/wt/releases/download/v0.1.0/wt_darwin_universal.tar.gz"
  sha256 "3e1f5a2bf6dd72dfe1fbfdbae5ca64ea07e89beaebc55b1fbd336de47dba42a3"

  def install
    bin.install "wt"
  end
end
