# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/joescharf/wt/releases/download/v0.2.0/wt_darwin_universal.tar.gz"
  sha256 "d3521423c084ae23a39176be81f31822de138aa688a54eabea5530bdd2b17a2c"

  def install
    bin.install "wt"
  end
end
