# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbsnapper < Formula
  desc "Create sanitized development snapshots of your production databases."
  homepage "https://dbsnapper.com/"
  version "2.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.0/dbsnapper_snapper_2.1.0_Darwin_x86_64.zip"
    sha256 "c40d13bdb607067c3c0697a2d01bfcc59824c48c48c47315752995b15a640dd5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.0/dbsnapper_snapper_2.1.0_Linux_x86_64.zip"
    sha256 "f1df4a33a812fb19037c9a46e0077622c7013ce2285c8144ca155c24fa5c3abd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.0/dbsnapper_snapper_2.1.0_Linux_arm64.zip"
    sha256 "d64352797cfbd105a8d1b7ac6a066b4795c651eda739a7933f8436e0b205051a"
  end

  def install
    bin.install "snapper"
  end
end
