# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snapper < Formula
  desc "Create sanitized development snapshots of your production databases."
  homepage "https://dbsnapper.com/"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joescharf/snapper/releases/download/v0.1.1/dbsnapper-cli_snapper_0.1.1_Darwin_x86_64.zip"
    sha256 "f488f0cc6a58ce56c123f1aab63013b4bf555d1425e0812a84226822d4e8aedc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/joescharf/snapper/releases/download/v0.1.1/dbsnapper-cli_snapper_0.1.1_Linux_x86_64.zip"
    sha256 "240d80c7f6212452be891a5f9e6ab73a96038ad83fb0a6dd5f2978770359b796"
  end

  def install
    bin.install "snapper"
  end
end
