# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snapper < Formula
  desc "Create sanitized development snapshots of your production databases."
  homepage "https://dbsnapper.com/"
  version "2.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.1/dbsnapper_snapper_2.1.1_Darwin_x86_64.zip"
    sha256 "de4baef11b80851cad6712f9a3d2b6ecfcb5c5099c54a80572f47284b724090c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.1/dbsnapper_snapper_2.1.1_Linux_x86_64.zip"
    sha256 "dacc10973033631132f4cccee69f53de05bb9d96fba06b31be2d7d7b2cd84331"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/joescharf/snapper/releases/download/v2.1.1/dbsnapper_snapper_2.1.1_Linux_arm64.zip"
    sha256 "d977ccde08ff899e0941fa74240f3f843c5d2c061ee3b85905a9d45af36d6d9a"
  end

  def install
    bin.install "snapper"
  end
end
