# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zfit < Formula
  desc "Zwift FIT file analyzer"
  homepage "https://joescharf.com/"
  version "0.1.0"

  on_macos do
    url "https://github.com/joescharf/zfit/releases/download/v0.1.0/zfit_zfit_0.1.0_Darwin_all.zip"
    sha256 "5d42334faf72a164c4cddc0e0bec0dd425a429e744591d16fe2761f276dc6b88"

    def install
      bin.install "zfit"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joescharf/zfit/releases/download/v0.1.0/zfit_zfit_0.1.0_Linux_x86_64.zip"
      sha256 "2428017306cfc53d06d1b6798aa316061e7be4ddb4bf64a9089dc5a59a1a1367"

      def install
        bin.install "zfit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/zfit/releases/download/v0.1.0/zfit_zfit_0.1.0_Linux_arm64.zip"
      sha256 "36e4112fa5d275daaa5a6f6e9f09a09fa4f96d6c35577aa9abbcbb12018808bc"

      def install
        bin.install "zfit"
      end
    end
  end
end
