# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zfit < Formula
  desc "Zwift FIT file analyzer"
  homepage "https://joescharf.com/"
  version "0.1.1"

  on_macos do
    url "https://github.com/joescharf/zfit/releases/download/v0.1.1/zfit_zfit_0.1.1_Darwin_all.zip"
    sha256 "1257c3b3e62e77715c805e662ba624cc84b755ffccfb1df99bc3d99b17000c15"

    def install
      bin.install "zfit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/zfit/releases/download/v0.1.1/zfit_zfit_0.1.1_Linux_arm64.zip"
      sha256 "1de959b8022ef2751e684d58d246363064393ce95ddf261b335a395bf05bc17d"

      def install
        bin.install "zfit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joescharf/zfit/releases/download/v0.1.1/zfit_zfit_0.1.1_Linux_x86_64.zip"
      sha256 "0b208db56d770326ac636345d815a29e885031fc550cc359b8e5bc3a9ddbed39"

      def install
        bin.install "zfit"
      end
    end
  end
end
